# Generated by Django 2.2 on 2019-04-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='recept',
            name='tag_name',
            field=models.ManyToManyField(to='Gluten.Tag'),
        ),
    ]
