# Generated by Django 2.2 on 2019-04-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeRecept',
        ),
    ]
