# Generated by Django 2.2 on 2019-04-18 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gluten', '0002_delete_likerecept'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRecept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=None)),
                ('recept', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gluten.Recept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
