# Generated by Django 2.2 on 2019-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0004_auto_20190413_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
