# Generated by Django 2.2 on 2019-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0005_recept_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество рецептов'),
        ),
    ]
