# Generated by Django 2.2 on 2019-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0006_auto_20190414_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/Users/moonlight/Documents/GlutenProject/GlutenFree/staticfiles/images/default.png', upload_to='media'),
        ),
    ]
