# Generated by Django 2.2 on 2019-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0007_auto_20190414_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
