# Generated by Django 2.2 on 2019-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0008_auto_20190414_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
