# Generated by Django 2.2 on 2019-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0010_auto_20190414_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='\u200e\u2068media/default.png', upload_to='media', verbose_name='Изображение профиля'),
        ),
    ]
