# Generated by Django 2.2 on 2019-04-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0011_auto_20190416_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recepts',
            new_name='recept',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время публикации'),
        ),
    ]
