# Generated by Django 2.2 on 2019-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gluten', '0013_auto_20190417_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='creater',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='Комментарий', max_length=200),
        ),
    ]
